services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432 # HTTP UI and API port
    volumes:
      - timescale:/var/lib/postgresql/data
      # - timescale:/home/postgres/pgdata/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=huawei-solar
      - TIMESCALEDB_TELEMETRY=off
  superset:
    build:
      context: ./Superset/
      args:
        - DATABASE_DISPLAY_NAME=Huawei Solar
        - DATABASE_DB=huawei-solar
        - DATABASE_HOST=timescale
        - DATABASE_USER=superset
        - DATABASE_PASSWORD=superset
        - DATABASE_PORT=5432
        - DATABASE_DIALECT=postgresql

    ports:
      - 80:8088
    volumes:
    - superset:/app/superset_home
    environment:
    - SECRET_KEY=qV4ZCA3qMX9f9xbJ1ZR92eY4WfJkvegpsqEfBL5uNIJTViK2Q2Snmj0s

  # cubejs:
  #   image: cubejs/cube:v0.31
  #   ports:
  #     - 4000:4000
  #     - 3000:3000
  #   environment:
  #     - CUBEJS_DEV_MODE=true
  #     - CUBEJS_DB_HOST=timescale
  #     - CUBEJS_DB_NAME=huawei-solar
  #     - CUBEJS_DB_USER=admin
  #     - CUBEJS_DB_PASS=adminpass
  #     - CUBEJS_DB_TYPE=postgres
  #   volumes:
  #     - ./cubejs:/cube/conf
volumes:
  timescale:
  superset:
