services:
  influxdb:
    image: influxdb:2.4
    ports:
      - 80:8086 # HTTP UI and API port
    volumes:
      - db-data:/var/lib/influxdb2
      - ./config.yml:/etc/influxdb2/config.yml
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=huawei-solar
      - DOCKER_INFLUXDB_INIT_BUCKET=huawei-solar
      - DOCKER_INFLUXDB_INTI_ADMIN_TOKEN=admintoken
  telegraf:
    image: telegraf:1.24
    ports:
      # - 8125:8125 # StatsD
      - 8092:8092 # UDP
      - 8094:8094 # TCP
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - TELEGRAF_TOKEN=D3nm6ALnMK0oNGG5mZ8eIrTvQwlA3oF3esS5HvGiZo04xSIe3-dOwUGUan08iYtvlBznRsSo1Sc75H5muiPfHA==
      - TELEGRAF_ORG=huawei-solar
      - TELEGRAF_BUCKET=huawei-solar
    depends_on:
      - influxdb
  redash:
    image: redash/redash:10.1.0.b50633
    ports:
      - 80:5000
    environment:
      - REDASH_COOKIE_SECRET=cookie_secret

volumes:
  db-data:
