[package]
name = "huawei-solar-collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
huawei_solar = { path = "../huawei-solar-rust"}
