[package]
name = "huawei_solar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modbus = "1.0.4"
bit-vec = "0.6.3"
thiserror = "1.0.58"
num = "0.4.1"
